// get products
export const GET_PRODUCTS_STARTED = 'GET_PRODUCTS_STARTED';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

// get product
export const GET_PRODUCT_STARTED = 'GET_PRODUCT_STARTED';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

// add new product
export const ON_CHANGE_PRODUCT_NAME = 'ON_CHANGE_PRODUCT_NAME';
export const ON_CHANGE_PRODUCT_ABOUT = 'ON_CHANGE_PRODUCT_ABOUT';
export const ON_CHANGE_PRODUCT_PRICE = 'ON_CHANGE_PRODUCT_PRICE';

// card
export const CLICK_BUTTON_PLUS = 'CLICK_BUTTON_PLUS';
export const CLICK_BUTTON_MINUS = 'CLICK_BUTTON_MINUS';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';

// on change order
export const ON_CHANGE_FIRST_NAME = 'ON_CHANGE_FIRST_NAME';
export const ON_CHANGE_LAST_NAME = 'ON_CHANGE_LAST_NAME';
export const ON_CHANGE_TEL = 'ON_CHANGE_TEL';
export const ON_CHANGE_STREET = 'ON_CHANGE_STREET';
export const ON_CHANGE_HOME = 'ON_CHANGE_HOME';
export const ON_CHANGE_APARTMENT = 'ON_CHANGE_APARTMENT';

// get orders
export const GET_ORDERS_STARTED = 'GET_ORDERS_STARTED';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';

// create order
export const CREATE_ORDER_STARTED = 'CREATE_ORDER_STARTED';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';