// get products
export const GET_PRODUCTS_STARTED = 'GET_PRODUCTS_STARTED';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

// add new product
export const ON_CHANGE_PRODUCT_NAME = 'ON_CHANGE_PRODUCT_NAME';
export const ON_CHANGE_PRODUCT_ABOUT = 'ON_CHANGE_PRODUCT_ABOUT';
export const ON_CHANGE_PRODUCT_PRICE = 'ON_CHANGE_PRODUCT_PRICE';