// get products
export const GET_PRODUCTS_STARTED = 'GET_PRODUCTS_STARTED';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

// add new product
export const ON_CHANGE_PRODUCT_NAME = 'ON_CHANGE_PRODUCT_NAME';
export const ON_CHANGE_PRODUCT_ABOUT = 'ON_CHANGE_PRODUCT_ABOUT';
export const ON_CHANGE_PRODUCT_PRICE = 'ON_CHANGE_PRODUCT_PRICE';

// card
export const CLICK_BUTTON_PLUS = 'CLICK_BUTTON_PLUS';
export const CLICK_BUTTON_MINUS = 'CLICK_BUTTON_MINUS';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';